export const COUNTRIES = [
  { name: 'United Kingdom', flag: '🇬🇧' },
  { name: 'United States', flag: '🇺🇸' },
  { name: 'Canada', flag: '🇨🇦' },
  { name: 'Australia', flag: '🇦🇺' },
  { name: 'China', flag: '🇨🇳' },
  { name: 'Germany', flag: '🇩🇪' },
  { name: 'Hungary', flag: '🇭🇺' },
  { name: 'Turkey', flag: '🇹🇷' },
  { name: 'Russia', flag: '🇷🇺' },
  { name: 'Japan', flag: '🇯🇵' },
  { name: 'South Korea', flag: '🇰🇷' },
  { name: 'France', flag: '🇫🇷' },
  { name: 'Italy', flag: '🇮🇹' },
  { name: 'Netherlands', flag: '🇳🇱' },
  { name: 'Norway', flag: '🇳🇴' },
  { name: 'Sweden', flag: '🇸🇪' },
  { name: 'Ethiopia', flag: '🇪🇹' },
  { name: 'Egypt', flag: '🇪🇬' },
  { name: 'South Africa', flag: '🇿🇦' },
  { name: 'Kenya', flag: '🇰🇪' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Ghana', flag: '🇬🇭' },
  { name: 'Singapore', flag: '🇸🇬' },
  { name: 'Malaysia', flag: '🇲🇾' },
  { name: 'India', flag: '🇮🇳' },
  { name: 'Thailand', flag: '🇹🇭' },
  { name: 'Vietnam', flag: '🇻🇳' },
  { name: 'Indonesia', flag: '🇮🇩' },
  { name: 'Philippines', flag: '🇵🇭' },
  { name: 'Brazil', flag: '🇧🇷' },
  { name: 'Mexico', flag: '🇲🇽' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Spain', flag: '🇪🇸' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Switzerland', flag: '🇨🇭' },
  { name: 'Austria', flag: '🇦🇹' },
  { name: 'Belgium', flag: '🇧🇪' },
  { name: 'Poland', flag: '🇵🇱' },
];

export const DEPARTMENTS = [
  'Any', 'Computer Science', 'Mechanical Engineering', 'Medicine', 
  'Economics', 'Psychology', 'Education', 'Architecture', 'Law', 'International Relations',
  'Business', 'Engineering', 'Agriculture', 'Nursing', 'Pharmacy', 'Journalism'
];

export const DEGREE_LEVELS = ['undergraduate', 'masters', 'phd', 'all'];

export const FIELDS_OF_STUDY = [
  'Any Field',
  'STEM & Tech',
  'Healthcare & Medicine',
  'Business & Economics',
  'Engineering',
  'Humanities & Social Sciences',
  'Arts & Design',
  'Law & Public Policy',
  'Agriculture & Environment',
];
