export interface CountryOption {
  label: string; // Country Name
  value: string; // ISO Code
  icon?: string; // Flag Emoji
}

export const ALL_COUNTRIES: CountryOption[] = [
  { value: 'AF', label: 'Afghanistan', icon: '🇦🇫' },
  { value: 'AL', label: 'Albania', icon: '🇦🇱' },
  { value: 'DZ', label: 'Algeria', icon: '🇩🇿' },
  { value: 'AS', label: 'American Samoa', icon: '🇦🇸' },
  { value: 'AD', label: 'Andorra', icon: '🇦🇩' },
  { value: 'AO', label: 'Angola', icon: '🇦🇴' },
  { value: 'AI', label: 'Anguilla', icon: '🇦🇮' },
  { value: 'AQ', label: 'Antarctica', icon: '🇦🇶' },
  { value: 'AG', label: 'Antigua and Barbuda', icon: '🇦🇬' },
  { value: 'AR', label: 'Argentina', icon: '🇦🇷' },
  { value: 'AM', label: 'Armenia', icon: '🇦🇲' },
  { value: 'AW', label: 'Aruba', icon: '🇦🇼' },
  { value: 'AU', label: 'Australia', icon: '🇦🇺' },
  { value: 'AT', label: 'Austria', icon: '🇦🇹' },
  { value: 'AZ', label: 'Azerbaijan', icon: '🇦🇿' },
  { value: 'BS', label: 'Bahamas', icon: '🇧🇸' },
  { value: 'BH', label: 'Bahrain', icon: '🇧🇭' },
  { value: 'BD', label: 'Bangladesh', icon: '🇧🇩' },
  { value: 'BB', label: 'Barbados', icon: '🇧🇧' },
  { value: 'BY', label: 'Belarus', icon: '🇧🇾' },
  { value: 'BE', label: 'Belgium', icon: '🇧🇪' },
  { value: 'BZ', label: 'Belize', icon: '🇧🇿' },
  { value: 'BJ', label: 'Benin', icon: '🇧🇯' },
  { value: 'BM', label: 'Bermuda', icon: '🇧🇲' },
  { value: 'BT', label: 'Bhutan', icon: '🇧🇹' },
  { value: 'BO', label: 'Bolivia', icon: '🇧🇴' },
  { value: 'BA', label: 'Bosnia and Herzegovina', icon: '🇧🇦' },
  { value: 'BW', label: 'Botswana', icon: '🇧🇼' },
  { value: 'BR', label: 'Brazil', icon: '🇧🇷' },
  { value: 'BN', label: 'Brunei', icon: '🇧🇳' },
  { value: 'BG', label: 'Bulgaria', icon: '🇧🇬' },
  { value: 'BF', label: 'Burkina Faso', icon: '🇧🇫' },
  { value: 'BI', label: 'Burundi', icon: '🇧🇮' },
  { value: 'KH', label: 'Cambodia', icon: '🇰🇭' },
  { value: 'CM', label: 'Cameroon', icon: '🇨🇲' },
  { value: 'CA', label: 'Canada', icon: '🇨🇦' },
  { value: 'CV', label: 'Cape Verde', icon: '🇨🇻' },
  { value: 'KY', label: 'Cayman Islands', icon: '🇰🇾' },
  { value: 'CF', label: 'Central African Republic', icon: '🇨🇫' },
  { value: 'TD', label: 'Chad', icon: '🇹🇩' },
  { value: 'CL', label: 'Chile', icon: '🇨🇱' },
  { value: 'CN', label: 'China', icon: '🇨🇳' },
  { value: 'CO', label: 'Colombia', icon: '🇨🇴' },
  { value: 'KM', label: 'Comoros', icon: '🇰🇲' },
  { value: 'CG', label: 'Congo', icon: '🇨🇬' },
  { value: 'CD', label: 'Congo, Democratic Republic', icon: '🇨🇩' },
  { value: 'CR', label: 'Costa Rica', icon: '🇨🇷' },
  { value: 'CI', label: "Cote d'Ivoire", icon: '🇨🇮' },
  { value: 'HR', label: 'Croatia', icon: '🇭🇷' },
  { value: 'CU', label: 'Cuba', icon: '🇨🇺' },
  { value: 'CY', label: 'Cyprus', icon: '🇨🇾' },
  { value: 'CZ', label: 'Czech Republic', icon: '🇨🇿' },
  { value: 'DK', label: 'Denmark', icon: '🇩🇰' },
  { value: 'DJ', label: 'Djibouti', icon: '🇩🇯' },
  { value: 'DM', label: 'Dominica', icon: '🇩🇲' },
  { value: 'DO', label: 'Dominican Republic', icon: '🇩🇴' },
  { value: 'EC', label: 'Ecuador', icon: '🇪🇨' },
  { value: 'EG', label: 'Egypt', icon: '🇪🇬' },
  { value: 'SV', label: 'El Salvador', icon: '🇸🇻' },
  { value: 'GQ', label: 'Equatorial Guinea', icon: '🇬🇶' },
  { value: 'ER', label: 'Eritrea', icon: '🇪🇷' },
  { value: 'EE', label: 'Estonia', icon: '🇪🇪' },
  { value: 'SZ', label: 'Eswatini', icon: '🇸🇿' },
  { value: 'ET', label: 'Ethiopia', icon: '🇪🇹' },
  { value: 'FJ', label: 'Fiji', icon: '🇫🇯' },
  { value: 'FI', label: 'Finland', icon: '🇫🇮' },
  { value: 'FR', label: 'France', icon: '🇫🇷' },
  { value: 'GA', label: 'Gabon', icon: '🇬🇦' },
  { value: 'GM', label: 'Gambia', icon: '🇬🇲' },
  { value: 'GE', label: 'Georgia', icon: '🇬🇪' },
  { value: 'DE', label: 'Germany', icon: '🇩🇪' },
  { value: 'GH', label: 'Ghana', icon: '🇬🇭' },
  { value: 'GR', label: 'Greece', icon: '🇬🇷' },
  { value: 'GD', label: 'Grenada', icon: '🇬🇩' },
  { value: 'GT', label: 'Guatemala', icon: '🇬🇹' },
  { value: 'GN', label: 'Guinea', icon: '🇬🇳' },
  { value: 'GW', label: 'Guinea-Bissau', icon: '🇬🇼' },
  { value: 'GY', label: 'Guyana', icon: '🇬🇾' },
  { value: 'HT', label: 'Haiti', icon: '🇭🇹' },
  { value: 'HN', label: 'Honduras', icon: '🇭🇳' },
  { value: 'HU', label: 'Hungary', icon: '🇭🇺' },
  { value: 'IS', label: 'Iceland', icon: '🇮🇸' },
  { value: 'IN', label: 'India', icon: '🇮🇳' },
  { value: 'ID', label: 'Indonesia', icon: '🇮🇩' },
  { value: 'IR', label: 'Iran', icon: '🇮🇷' },
  { value: 'IQ', label: 'Iraq', icon: '🇮🇶' },
  { value: 'IE', label: 'Ireland', icon: '🇮🇪' },
  { value: 'IL', label: 'Israel', icon: '🇮🇱' },
  { value: 'IT', label: 'Italy', icon: '🇮🇹' },
  { value: 'JM', label: 'Jamaica', icon: '🇯🇲' },
  { value: 'JP', label: 'Japan', icon: '🇯🇵' },
  { value: 'JO', label: 'Jordan', icon: '🇯🇴' },
  { value: 'KZ', label: 'Kazakhstan', icon: '🇰🇿' },
  { value: 'KE', label: 'Kenya', icon: '🇰🇪' },
  { value: 'KI', label: 'Kiribati', icon: '🇰🇮' },
  { value: 'KP', label: 'Korea, North', icon: '🇰🇵' },
  { value: 'KR', label: 'Korea, South', icon: '🇰🇷' },
  { value: 'KW', label: 'Kuwait', icon: '🇰🇼' },
  { value: 'KG', label: 'Kyrgyzstan', icon: '🇰🇬' },
  { value: 'LA', label: 'Laos', icon: '🇱🇦' },
  { value: 'LV', label: 'Latvia', icon: '🇱🇻' },
  { value: 'LB', label: 'Lebanon', icon: '🇱🇧' },
  { value: 'LS', label: 'Lesotho', icon: '🇱🇸' },
  { value: 'LR', label: 'Liberia', icon: '🇱🇷' },
  { value: 'LY', label: 'Libya', icon: '🇱🇾' },
  { value: 'LI', label: 'Liechtenstein', icon: '🇱🇮' },
  { value: 'LT', label: 'Lithuania', icon: '🇱🇹' },
  { value: 'LU', label: 'Luxembourg', icon: '🇱🇺' },
  { value: 'MG', label: 'Madagascar', icon: '🇲🇬' },
  { value: 'MW', label: 'Malawi', icon: '🇲🇼' },
  { value: 'MY', label: 'Malaysia', icon: '🇲🇾' },
  { value: 'MV', label: 'Maldives', icon: '🇲🇻' },
  { value: 'ML', label: 'Mali', icon: '🇲🇱' },
  { value: 'MT', label: 'Malta', icon: '🇲🇹' },
  { value: 'MH', label: 'Marshall Islands', icon: '🇲🇭' },
  { value: 'MR', label: 'Mauritania', icon: '🇲🇷' },
  { value: 'MU', label: 'Mauritius', icon: '🇲🇺' },
  { value: 'MX', label: 'Mexico', icon: '🇲🇽' },
  { value: 'FM', label: 'Micronesia', icon: '🇫🇲' },
  { value: 'MD', label: 'Moldova', icon: '🇲🇩' },
  { value: 'MC', label: 'Monaco', icon: '🇲🇨' },
  { value: 'MN', label: 'Mongolia', icon: '🇲🇳' },
  { value: 'ME', label: 'Montenegro', icon: '🇲🇪' },
  { value: 'MA', label: 'Morocco', icon: '🇲🇦' },
  { value: 'MZ', label: 'Mozambique', icon: '🇲🇿' },
  { value: 'MM', label: 'Myanmar', icon: '🇲🇲' },
  { value: 'NA', label: 'Namibia', icon: '🇳🇦' },
  { value: 'NR', label: 'Nauru', icon: '🇳🇷' },
  { value: 'NP', label: 'Nepal', icon: '🇳🇵' },
  { value: 'NL', label: 'Netherlands', icon: '🇳🇱' },
  { value: 'NZ', label: 'New Zealand', icon: '🇳🇿' },
  { value: 'NI', label: 'Nicaragua', icon: '🇳🇮' },
  { value: 'NE', label: 'Niger', icon: '🇳🇪' },
  { value: 'NG', label: 'Nigeria', icon: '🇳🇬' },
  { value: 'NO', label: 'Norway', icon: '🇳🇴' },
  { value: 'OM', label: 'Oman', icon: '🇴🇲' },
  { value: 'PK', label: 'Pakistan', icon: '🇵🇰' },
  { value: 'PW', label: 'Palau', icon: '🇵🇼' },
  { value: 'PA', label: 'Panama', icon: '🇵🇦' },
  { value: 'PG', label: 'Papua New Guinea', icon: '🇵🇬' },
  { value: 'PY', label: 'Paraguay', icon: '🇵🇾' },
  { value: 'PE', label: 'Peru', icon: '🇵🇪' },
  { value: 'PH', label: 'Philippines', icon: '🇵🇭' },
  { value: 'PL', label: 'Poland', icon: '🇵🇱' },
  { value: 'PT', label: 'Portugal', icon: '🇵🇹' },
  { value: 'QA', label: 'Qatar', icon: '🇶🇦' },
  { value: 'RO', label: 'Romania', icon: '🇷🇴' },
  { value: 'RU', label: 'Russia', icon: '🇷🇺' },
  { value: 'RW', label: 'Rwanda', icon: '🇷🇼' },
  { value: 'KN', label: 'Saint Kitts and Nevis', icon: '🇰🇳' },
  { value: 'LC', label: 'Saint Lucia', icon: '🇱🇨' },
  { value: 'VC', label: 'Saint Vincent', icon: '🇻🇨' },
  { value: 'WS', label: 'Samoa', icon: '🇼🇸' },
  { value: 'SM', label: 'San Marino', icon: '🇸🇲' },
  { value: 'ST', label: 'Sao Tome and Principe', icon: '🇸🇹' },
  { value: 'SA', label: 'Saudi Arabia', icon: '🇸🇦' },
  { value: 'SN', label: 'Senegal', icon: '🇸🇳' },
  { value: 'RS', label: 'Serbia', icon: '🇷🇸' },
  { value: 'SC', label: 'Seychelles', icon: '🇸🇨' },
  { value: 'SL', label: 'Sierra Leone', icon: '🇸🇱' },
  { value: 'SG', label: 'Singapore', icon: '🇸🇬' },
  { value: 'SK', label: 'Slovakia', icon: '🇸🇰' },
  { value: 'SI', label: 'Slovenia', icon: '🇸🇮' },
  { value: 'SB', label: 'Solomon Islands', icon: '🇸🇧' },
  { value: 'SO', label: 'Somalia', icon: '🇸🇴' },
  { value: 'ZA', label: 'South Africa', icon: '🇿🇦' },
  { value: 'SS', label: 'South Sudan', icon: '🇸🇸' },
  { value: 'ES', label: 'Spain', icon: '🇪🇸' },
  { value: 'LK', label: 'Sri Lanka', icon: '🇱🇰' },
  { value: 'SD', label: 'Sudan', icon: '🇸🇩' },
  { value: 'SR', label: 'Suriname', icon: '🇸🇷' },
  { value: 'SE', label: 'Sweden', icon: '🇸🇪' },
  { value: 'CH', label: 'Switzerland', icon: '🇨🇭' },
  { value: 'SY', label: 'Syria', icon: '🇸🇾' },
  { value: 'TW', label: 'Taiwan', icon: '🇹🇼' },
  { value: 'TJ', label: 'Tajikistan', icon: '🇹🇯' },
  { value: 'TZ', label: 'Tanzania', icon: '🇹🇿' },
  { value: 'TH', label: 'Thailand', icon: '🇹🇭' },
  { value: 'TG', label: 'Togo', icon: '🇹🇬' },
  { value: 'TO', label: 'Tonga', icon: '🇹🇴' },
  { value: 'TT', label: 'Trinidad and Tobago', icon: '🇹🇹' },
  { value: 'TN', label: 'Tunisia', icon: '🇹🇳' },
  { value: 'TR', label: 'Turkey', icon: '🇹🇷' },
  { value: 'TM', label: 'Turkmenistan', icon: '🇹🇲' },
  { value: 'TV', label: 'Tuvalu', icon: '🇹🇻' },
  { value: 'UG', label: 'Uganda', icon: '🇺🇬' },
  { value: 'UA', label: 'Ukraine', icon: '🇺🇦' },
  { value: 'AE', label: 'United Arab Emirates', icon: '🇦🇪' },
  { value: 'GB', label: 'United Kingdom', icon: '🇬🇧' },
  { value: 'US', label: 'United States', icon: '🇺🇸' },
  { value: 'UY', label: 'Uruguay', icon: '🇺🇾' },
  { value: 'UZ', label: 'Uzbekistan', icon: '🇺🇿' },
  { value: 'VU', label: 'Vanuatu', icon: '🇻🇺' },
  { value: 'VE', label: 'Venezuela', icon: '🇻🇪' },
  { value: 'VN', label: 'Vietnam', icon: '🇻🇳' },
  { value: 'YE', label: 'Yemen', icon: '🇾🇪' },
  { value: 'ZM', label: 'Zambia', icon: '🇿🇲' },
  { value: 'ZW', label: 'Zimbabwe', icon: '🇿🇼' }
];
